// Statik sayfaların (rehberler, gizlilik) ve ana sayfa meta metinlerinin kaynağı.
// scripts/build-pages.mjs bunlardan dist/pages/ altında HTML ve manifest.json üretir.
// Metin biçimi: **kalın**, [bağlantı](adres). Bloklar: { h2 }, { p }, { ul: [] }, { ol: [] }.

export const UPDATED = '2026-10-09';

export const home = {
  tr: {
    title: 'SprintMasası · Ücretsiz online planning poker',
    description:
      'Ekibinle ücretsiz, hesapsız planning poker (scrum poker) oyna: story point tahmini, kartlar aynı anda açılır, ticket kuyruğu ve işi kimin alacağını seçen eğlenceli oyunlar. Link yeter.',
    ogDescription: 'Ekibinle eğlenceli ve adil sprint planlama. Hesap yok, link yeter.',
    locale: 'tr_TR',
    boot: {
      h1: 'SprintMasası',
      p: 'Ekibinle ücretsiz online planning poker. Hesap yok, link yeter: oda kur, kartlar aynı anda açılsın, işi kimin alacağını at yarışı ya da çark seçsin.',
      cta: 'Oda oluştur',
    },
  },
  en: {
    title: 'SprintMasası · Free online planning poker',
    description:
      'Free planning poker (scrum poker) for your team, no sign-up: story point estimates, cards flip together, a ticket queue, and fun games that decide who takes the work. Just share a link.',
    ogDescription: 'Fun, fair sprint planning with your team. No account, just a link.',
    locale: 'en_US',
    boot: {
      h1: 'SprintMasası',
      p: 'Free online planning poker for your team. No account, just a link: open a room, flip the cards together, and let a horse race or a wheel decide who takes the work.',
      cta: 'Create a room',
    },
  },
};

export const ui = {
  tr: {
    brand: 'SprintMasası',
    nav: 'Gezinti',
    guide: 'Planning poker nedir?',
    storyPoints: 'Story point rehberi',
    privacy: 'Gizlilik',
    source: 'Kaynak kod',
    cta: 'Oda oluştur',
    ctaPath: '/yeni?lang=tr',
    otherLang: 'English',
    updated: 'Son güncelleme',
    footerNote: 'Ücretsiz, hesapsız planning poker.',
    dateFmt: '9 Ekim 2026',
  },
  en: {
    brand: 'SprintMasası',
    nav: 'Navigation',
    guide: 'What is planning poker?',
    storyPoints: 'Story points guide',
    privacy: 'Privacy',
    source: 'Source code',
    cta: 'Create a room',
    ctaPath: '/yeni?lang=en',
    otherLang: 'Türkçe',
    updated: 'Last updated',
    footerNote: 'Free planning poker, no account needed.',
    dateFmt: 'October 9, 2026',
  },
};

export const pages = [
  // ------------------------------------------------------------------ Türkçe
  {
    id: 'guide',
    lang: 'tr',
    path: '/planning-poker-nedir',
    title: 'Planning Poker Nedir? Nasıl Oynanır? | SprintMasası',
    description:
      'Planning poker (scrum poker) nedir, nasıl oynanır, hangi desteyi seçmeli? Çevik ekipler için adım adım rehber ve ücretsiz online masa.',
    h1: 'Planning poker nedir, nasıl oynanır?',
    lead:
      'Planning poker (scrum poker), çevik ekiplerin işleri birlikte ve birbirini etkilemeden tahmin etmesini sağlayan bir kart oyunudur. Herkes aynı anda gizli bir kart seçer, kartlar birlikte açılır; tahminler ayrışırsa ekip konuşur ve yeniden oylar.',
    blocks: [
      { h2: 'Neden oynanır?' },
      { p: 'Bir toplantıda ilk söyleyenin sayısı çoğu zaman diğerlerini yönlendirir. Planning poker bunu engeller: kartlar açılana kadar kimse başkasının tahminini bilmez. Böylece en deneyimli kişi kadar yeni gelen de görüşünü saklamadan söyler ve ekip, işin neresinde ayrıştığını görür.' },
      { p: 'Asıl değer sayının kendisinde değil, aradaki farkın konuşulmasında. "Sen neden 13 verdin, ben 3 verdim?" sorusu çoğu zaman eksik bir varsayımı ya da unutulmuş bir bağımlılığı ortaya çıkarır.' },
      { h2: 'Kısa tarihçe' },
      { p: 'Yöntemi 2002\'de James Grenning anlattı; Mike Cohn "Agile Estimating and Planning" kitabıyla yaygınlaştırdı. Bugün Scrum ekiplerinin sprint planlama ve backlog rafine etme toplantılarında en sık kullandığı tahmin yöntemlerinden biridir.' },
      { h2: 'Adım adım nasıl oynanır?' },
      { ol: [
        '**Hazırlık:** Ekip bir deste seçer (aşağıya bak) ve oylanacak işi, yani hikâyeyi ya da ticket\'ı belirler.',
        '**Anlatım:** Ürün sahibi ya da işi bilen kişi kısaca anlatır; ekip soru sorar. Bu aşamada sayı söylenmez.',
        '**Gizli oy:** Herkes işi bildiği kadarıyla bir kart seçer ve kapalı tutar.',
        '**Açılış:** Krupiye (oyunu yöneten kişi) kartları birlikte açar.',
        '**Konuşma:** Herkes aynı sayıyı seçtiyse iş biter. Değilse en düşük ve en yüksek oyu verenler gerekçelerini anlatır.',
        '**Yeniden oy:** Konuşmadan sonra yeniden oylanır. Genellikle bir ya da iki turda yakınsar; üç turdan fazla sürüyorsa iş muhtemelen bölünmeli ya da önce araştırılmalıdır.',
      ] },
      { h2: 'Hangi desteyi seçmeli?' },
      { ul: [
        '**Fibonacci (0, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89):** İş büyüdükçe belirsizlik de büyür; sayılar arasındaki boşluk bu yüzden açılır. En yaygın seçimdir.',
        '**Modifiye Fibonacci (0, ½, 1, 2, 3, 5, 8, 13, 21, 34, 55):** Fibonacci\'ye çok küçük işler için ½ kartını ekler. SprintMasası\'nda varsayılan budur.',
        '**T-shirt (XS, S, M, L, XL):** Sayı yerine beden kullanmak isteyen ya da backlog\'u kabaca ayıran ekipler için.',
        '**Özel deste:** Kendi ölçeğini kurmak istersen kartları kendin yazarsın.',
      ] },
      { p: '"?" kartı "bu işi anlamadım" demektir, mola kartı ise ara vermeyi önerir. İkisi de ortalamaya katılmaz.' },
      { h2: 'Daha iyi oturumlar için ipuçları' },
      { ul: [
        '**Referans bir iş seç:** Ekibin iyi bildiği bir işe örneğin 3 puan verin ve diğerlerini ona göre kıyaslayın.',
        '**Süre koy:** Her iş için birkaç dakikalık sayaç tartışmanın uzamasını önler.',
        '**Uçları dinle:** Sonucu ortalamayla kapatmak yerine en yüksek ve en düşük oyu verenlere söz ver.',
        '**Büyük işi böl:** 13 ve üstü çıkan işler genellikle tek sprintte bitmez; daha küçük parçalara ayırmak tahmini de iyileştirir.',
        '**Herkes oynasın:** Geliştirme, test ve tasarım birlikte oylarsa gizli işler daha erken görünür.',
      ] },
      { h2: 'SprintMasası ile oynamak' },
      { p: 'SprintMasası, bu akışı tarayıcıda, hesap açmadan oynatır: oda kurarsın, linki ekibe gönderirsin, herkes avatarını seçip masaya oturur.' },
      { ul: [
        'Kartlar kapalı oylanır ve krupiye açınca birlikte döner; istersen herkes oy verince kendiliğinden açılır.',
        'Dağılım, ortalama, medyan ve uzlaşı seviyesi açılışta masada görünür.',
        'İsteğe bağlı ticket kuyruğu: işleri sırayla oyla, final tahminleri oturum geçmişinde tut.',
        'Süre sayacı, gözlemci modu ve isteğe bağlı oda şifresi.',
        '"Kim alacak?": gönüllü yoksa at yarışı ya da şans çarkı işi kimin alacağına karar verir; kazananı sunucu belirler.',
      ] },
      { cta: true },
      { h2: 'Sık sorulanlar' },
      { h3: 'Kaç kişiyle oynanır?' },
      { p: 'Verimli oturumlar genellikle 3 ile 9 kişi arasındadır. SprintMasası bir odada 100 kişiye kadar izin verir, ama büyük gruplarda tartışmayı sınırlamak için gözlemci modunu kullanmak iyi olur.' },
      { h3: 'Ücretsiz mi, hesap gerekiyor mu?' },
      { p: 'Ücretsiz ve hesap gerektirmiyor. Oda linkini paylaşmak yeterli.' },
      { h3: 'Verilerim saklanıyor mu?' },
      { p: 'Odalar yalnızca sunucu belleğinde yaşar ve kapanınca silinir. Ayrıntılar için [gizlilik sayfasına](/gizlilik) bak.' },
      { h3: 'Puanları nasıl belirlerim?' },
      { p: 'Puanın ne anlama geldiği için [story point rehberine](/story-point-nedir) göz atabilirsin.' },
    ],
  },
  {
    id: 'storyPoints',
    lang: 'tr',
    path: '/story-point-nedir',
    title: 'Story Point Nedir? Fibonacci ile Tahmin Rehberi | SprintMasası',
    description:
      'Story point nedir, neden saat yerine kullanılır, Fibonacci dizisi neden tercih edilir? Velocity, referans hikâye ve sık yapılan hatalar.',
    h1: 'Story point nedir?',
    lead:
      'Story point (hikâye puanı), bir işin büyüklüğünü saat ya da gün yerine göreli bir ölçekle ifade eder. Puan; yapılacak iş miktarını, karmaşıklığı ve belirsizliği birlikte yansıtır.',
    blocks: [
      { h2: 'Süre yerine neden puan?' },
      { p: 'Aynı işi bir kişi iki saatte, bir başkası iki günde bitirebilir; tahmin eden kişiye göre değişen süre ekipçe konuşmayı zorlaştırır. İşleri birbiriyle kıyaslamak ise daha tutarlıdır: "Bu iş şu işten yaklaşık iki kat büyük" demek, kimin yapacağından bağımsız bir cümledir.' },
      { p: 'Puan süreye çevrilmez. Ekip zamanla kaç puanlık işi bir sprintte bitirdiğini görür ve plan buna dayanır.' },
      { h2: 'Fibonacci neden kullanılır?' },
      { p: 'Fibonacci benzeri dizi (1, 2, 3, 5, 8, 13, 21) büyüdükçe adımları açar. Küçük işlerde 2 ile 3 arasındaki farkı ayırt edebiliriz; büyük işlerde 20 ile 21 arasındaki farkı ayırt edemeyiz. Dizi bu gerçeği yansıtır ve gereksiz tartışmayı keser: iş 8 ile 13 arasındaysa ekip hangisine daha yakın olduğuna karar verir, 10 ya da 11 demez.' },
      { h2: 'Bir puan neyi ifade eder?' },
      { p: 'Ölçek her ekipte farklıdır; önemli olan ekibin kendi içinde tutarlı olmasıdır. Başlangıç için örnek bir okuma:' },
      { ul: [
        '**1:** Çok küçük ve iyi bilinen iş; ne yapılacağı belli.',
        '**2 – 3:** Küçük iş; bir iki küçük belirsizlik olabilir.',
        '**5 – 8:** Orta büyüklükte iş; birkaç parçaya dokunur, bir miktar araştırma gerekebilir.',
        '**13 ve üstü:** Büyük ya da belirsiz iş; bölmeyi ya da önce bir araştırma işi açmayı düşün.',
      ] },
      { h2: 'Referans hikâye ile kalibre et' },
      { p: 'Ekibin iyi bildiği bir işi seçip ona sabit bir puan verin; örneğin "giriş sayfasındaki alan doğrulaması 3 puandır". Sonraki işler için sorulacak soru "kaç saat sürer?" değil, "bu, referanstan küçük mü, aynı mı, büyük mü?" olur. Referansı zaman zaman gözden geçirin.' },
      { h2: 'Velocity ve planlama' },
      { p: 'Velocity, bir sprintte tamamlanan işlerin puan toplamıdır. Son birkaç sprintin ortalaması, bir sonraki sprint için gerçekçi bir hedef verir. Velocity ekibin kendi planlama aracıdır; ekipler arasında kıyaslanmamalı ve performans ölçüsü olarak kullanılmamalıdır, yoksa puanlar şişmeye başlar.' },
      { h2: 'Sık yapılan hatalar' },
      { ul: [
        '**Puanı saate çevirmek:** "1 puan = 4 saat" dedikten sonra göreli tahminin faydası kalmaz.',
        '**Her kişinin kendi ölçeğiyle puan vermesi:** Ortak referans yoksa sayılar karşılaştırılamaz.',
        '**Büyük işleri bölmeden puanlamak:** 21 ya da 40 puanlık bir iş çoğunlukla tahmin değil, tahmin edilememiş bir iştir.',
        '**Sprint içinde puanı değiştirmek:** Yanlış çıkan tahmin bir sonraki tahmin için ders olsun; geçmiş velocity\'yi bozmayın.',
        '**Sonucu tartışmasız ortalamayla kapatmak:** Aykırı oylar çoğu zaman en değerli bilgidir.',
      ] },
      { h2: 'Planning poker ile birlikte' },
      { p: 'Story point\'leri belirlemenin en yaygın yolu [planning poker](/planning-poker-nedir) oynamaktır: herkes gizlice bir puan seçer, kartlar birlikte açılır ve ayrışma konuşulur. SprintMasası bunu hesap açmadan, tarayıcıda oynatır.' },
      { cta: true },
    ],
  },
  {
    id: 'privacy',
    lang: 'tr',
    path: '/gizlilik',
    title: 'Gizlilik | SprintMasası',
    description:
      'SprintMasası hangi bilgileri işler, ne kadar saklar? Hesap yok, çerez yok, takip yok: odalar yalnızca sunucu belleğinde yaşar.',
    h1: 'Gizlilik',
    lead:
      'SprintMasası hesap, e-posta ya da telefon istemez; çerez kullanmaz, reklam ve izleme aracı içermez. Odadaki bilgiler yalnızca sunucu belleğinde tutulur ve oda kapanınca silinir.',
    blocks: [
      { h2: 'Hangi bilgiler işlenir?' },
      { p: 'Bir odada yazdıkların ve seçtiklerin sunucuya gönderilir, çünkü masadaki herkesin aynı şeyi görmesi gerekir:' },
      { ul: [
        'takma adın ve avatarın,',
        'verdiğin oylar ve seçtiğin deste,',
        'oda adı, konu ve eklenen ticket başlıkları, linkleri ve notları,',
        'oda şifresi (yalnızca geri döndürülemeyen bir özet olarak saklanır).',
      ] },
      { p: 'Bu bilgiler diske ya da veritabanına yazılmaz; yalnızca çalışan sunucunun belleğinde durur.' },
      { h2: 'Ne kadar süre saklanır?' },
      { ul: [
        'Krupiye odayı kapattığında oda ve içindeki her şey silinir.',
        'Kimsenin bağlı olmadığı oda, son hareketten 7 gün sonra otomatik silinir.',
        'Sunucu yeniden başladığında ya da yeni sürüm yayınlandığında tüm odalar silinir.',
      ] },
      { h2: 'Tarayıcında saklananlar' },
      { p: 'Sayfayı yenilediğinde aynı koltuğa dönebilmen için tarayıcının yerel depolamasında (localStorage) bir koltuk anahtarı tutulur. Ayrıca takma adın, avatarın, tema, ses ve dil tercihin saklanır. Bunlar çerez değildir, izleme amacıyla kullanılmaz ve tarayıcı verilerini temizleyerek silebilirsin.' },
      { h2: 'Günlükler ve IP adresi' },
      { p: 'Uygulamanın günlüklerine yalnızca oda kodu ve olay türü yazılır ("oda açıldı" gibi); isim, oy ya da ticket içeriği yazılmaz. Kötüye kullanımı sınırlamak için IP adresin, birkaç dakikalık hız sınırı sayaçlarında bellekte kullanılır ve kalıcı saklanmaz.' },
      { p: 'Sunucuyu barındıran Render, kendi altyapı günlüklerinde IP adresini tutabilir. Bu kayıtlar bizim kontrolümüzde değildir; ayrıntı için [Render gizlilik politikasına](https://render.com/privacy) bak.' },
      { h2: 'İstatistikler' },
      { p: 'Kaç oda açıldığı, odalardaki ortalama katılımcı sayısı, açılan tur sayısı gibi yalnızca toplam sayılar tutulur. Bu sayılar kişilerle ya da odaların içeriğiyle ilişkilendirilemez. Üçüncü taraf analiz, reklam ya da izleme aracı kullanılmaz.' },
      { h2: 'Üçüncü taraflar' },
      { p: 'Yazı tipleri, görseller ve avatarlar kendi sunucumuzdan gelir; Google Fonts, CDN ya da harici avatar servisi çağrılmaz. Ticket linkine tıkladığında ilgili sitenin kendi kurallarına tabi olursun.' },
      { h2: 'Güvenlik ve dikkat edilecekler' },
      { ul: [
        'Bağlantı HTTPS ile şifrelenir.',
        'Oda kodları tahmin edilemeyecek biçimde rastgele üretilir; ancak linki bilen herkes şifresiz odaya girebilir.',
        'Ticket başlıkların şirket içi bilgi içeriyorsa odaya şifre koy.',
        'Ticket ve not alanlarına parola, kişisel veri ya da gizli bilgi yazma.',
      ] },
      { h2: 'Haklarınız ve iletişim' },
      { p: 'Kişisel verilerin korunmasına ilişkin mevzuat (KVKK ve GDPR) kapsamındaki haklarını kullanmak ya da soru sormak için [GitHub proje sayfasından](https://github.com/rossven/scrum-poker/issues) bize ulaşabilirsin. Odalardaki bilgiler kalıcı saklanmadığı için çoğu durumda silinecek bir kayıt zaten bulunmaz. Verileri işleyen taraf, SprintMasası\'nı işleten proje sahibidir (GitHub: rossven).' },
      { h2: 'Değişiklikler' },
      { p: 'Uygulama değişirse bu sayfa güncellenir; sayfanın altındaki tarih son güncellemeyi gösterir.' },
    ],
    noCta: true,
  },

  // ------------------------------------------------------------------ English
  {
    id: 'guide',
    lang: 'en',
    path: '/en/what-is-planning-poker',
    title: 'What Is Planning Poker and How Do You Play It? | SprintMasası',
    description:
      'What planning poker (scrum poker) is, how to play it step by step, and which deck to pick. A practical guide for agile teams plus a free online table.',
    h1: 'What is planning poker and how do you play it?',
    lead:
      'Planning poker (also called scrum poker) is a card game agile teams use to estimate work together without influencing each other. Everyone picks a card in secret, the cards are revealed at the same time, and if the estimates differ the team discusses and votes again.',
    blocks: [
      { h2: 'Why play it?' },
      { p: 'In a meeting, the first number spoken often steers everyone else. Planning poker prevents that: nobody sees another estimate until the cards are revealed. The most experienced person and the newest teammate both say what they think, and the team sees exactly where it disagrees.' },
      { p: 'The real value is not the number but the conversation about the gap. "Why did you pick 13 when I picked 3?" often uncovers a missing assumption or a forgotten dependency.' },
      { h2: 'A short history' },
      { p: 'James Grenning described the technique in 2002, and Mike Cohn popularized it in his book "Agile Estimating and Planning". Today it is one of the most common estimation methods in Scrum sprint planning and backlog refinement.' },
      { h2: 'How to play, step by step' },
      { ol: [
        '**Prepare:** The team picks a deck (see below) and the item to estimate, a story or a ticket.',
        '**Explain:** The product owner or whoever knows the item describes it briefly and the team asks questions. No numbers yet.',
        '**Vote in secret:** Everyone picks a card based on what they know and keeps it face down.',
        '**Reveal:** The dealer (whoever runs the session) flips all cards at once.',
        '**Discuss:** If everyone picked the same number, you are done. If not, the people with the lowest and highest votes explain their reasoning.',
        '**Vote again:** After the discussion, vote again. It usually converges in one or two rounds; if it takes more than three, the item probably needs to be split or researched first.',
      ] },
      { h2: 'Which deck should you use?' },
      { ul: [
        '**Fibonacci (0, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89):** The bigger the work, the bigger the uncertainty, so the gaps between numbers widen. The most common choice.',
        '**Modified Fibonacci (0, ½, 1, 2, 3, 5, 8, 13, 21, 34, 55):** Fibonacci plus a ½ card for very small items. This is the default in SprintMasası.',
        '**T-shirt sizes (XS, S, M, L, XL):** For teams that prefer sizes over numbers, or for roughly sorting a backlog.',
        '**Custom deck:** Write your own cards if you want your own scale.',
      ] },
      { p: 'A "?" card means "I do not understand this item", and the break card suggests taking a pause. Neither counts toward the average.' },
      { h2: 'Tips for better sessions' },
      { ul: [
        '**Pick a reference item:** Give a well-known item a fixed value, say 3 points, and compare everything else to it.',
        '**Use a timer:** A few minutes per item keeps discussions from dragging on.',
        '**Listen to the extremes:** Instead of settling on the average, give the floor to the highest and lowest voters.',
        '**Split big items:** Items that land on 13 or more rarely fit in a single sprint; breaking them down also improves the estimate.',
        '**Let everyone play:** When developers, testers and designers vote together, hidden work shows up earlier.',
      ] },
      { h2: 'Playing with SprintMasası' },
      { p: 'SprintMasası runs this flow in your browser without an account: you open a room, send the link to your team, and everyone picks an avatar and takes a seat.' },
      { ul: [
        'Cards are voted face down and flip together when the dealer reveals; optionally they flip on their own once everyone has voted.',
        'The spread, average, median and level of agreement appear on the table at the reveal.',
        'An optional ticket queue: estimate items one by one and keep the final estimates in the session history.',
        'A timer, an observer mode and an optional room password.',
        '"Who takes it?": if nobody volunteers, a horse race or a wheel decides who takes the work, and the server picks the winner.',
      ] },
      { cta: true },
      { h2: 'Frequently asked questions' },
      { h3: 'How many people can play?' },
      { p: 'Productive sessions usually have 3 to 9 people. SprintMasası allows up to 100 in a room, but in large groups it helps to put some people in observer mode to keep the discussion focused.' },
      { h3: 'Is it free, and do I need an account?' },
      { p: 'It is free and needs no account. Sharing the room link is enough.' },
      { h3: 'Is my data stored?' },
      { p: 'Rooms live only in server memory and are deleted when they close. See the [privacy page](/en/privacy) for details.' },
      { h3: 'How do I decide the points?' },
      { p: 'For what a point means, read the [story points guide](/en/story-points-guide).' },
    ],
  },
  {
    id: 'storyPoints',
    lang: 'en',
    path: '/en/story-points-guide',
    title: 'What Are Story Points? A Guide to Fibonacci Estimation | SprintMasası',
    description:
      'What story points are, why teams use them instead of hours, and why the Fibonacci sequence works. Velocity, reference stories and common mistakes.',
    h1: 'What are story points?',
    lead:
      'A story point expresses the size of a piece of work on a relative scale instead of in hours or days. A point reflects the amount of work, its complexity and its uncertainty together.',
    blocks: [
      { h2: 'Why points instead of time?' },
      { p: 'One person may finish an item in two hours and another in two days; a time that depends on who estimates makes team conversations harder. Comparing items with each other is more consistent: "this is about twice as big as that one" holds no matter who ends up doing it.' },
      { p: 'Points are not converted to time. Over a few sprints the team sees how many points it finishes per sprint, and planning is based on that.' },
      { h2: 'Why Fibonacci?' },
      { p: 'A Fibonacci-like sequence (1, 2, 3, 5, 8, 13, 21) widens its steps as the numbers grow. On small items we can tell 2 from 3; on large items we cannot tell 20 from 21. The sequence reflects that and cuts pointless debate: if an item sits between 8 and 13, the team decides which it is closer to instead of arguing for 10 or 11.' },
      { h2: 'What does a point mean?' },
      { p: 'Every team\'s scale differs; what matters is being consistent within the team. A starting point you can adapt:' },
      { ul: [
        '**1:** Very small and well understood; it is clear what to do.',
        '**2 – 3:** Small; there may be a minor unknown or two.',
        '**5 – 8:** Medium; touches several parts and may need some investigation.',
        '**13 and above:** Large or uncertain; consider splitting it or opening a research task first.',
      ] },
      { h2: 'Calibrate with a reference story' },
      { p: 'Pick an item the team knows well and give it a fixed value, for example "field validation on the login page is 3 points". For later items the question becomes not "how many hours?" but "is this smaller than, the same as, or bigger than the reference?". Revisit the reference once in a while.' },
      { h2: 'Velocity and planning' },
      { p: 'Velocity is the sum of points for the items completed in a sprint. The average of the last few sprints gives a realistic target for the next one. Velocity is a team\'s own planning tool; it should not be compared across teams or used as a performance measure, or the points start to inflate.' },
      { h2: 'Common mistakes' },
      { ul: [
        '**Converting points to hours:** Once you say "1 point = 4 hours", the benefit of relative estimation is gone.',
        '**Everyone using their own scale:** Without a shared reference the numbers cannot be compared.',
        '**Pointing big items without splitting them:** A 21 or 40 point item is usually not an estimate but an item nobody could estimate.',
        '**Changing points mid-sprint:** Let a wrong estimate teach the next one; do not rewrite historical velocity.',
        '**Settling on the average without discussion:** Outlier votes are often the most valuable information.',
      ] },
      { h2: 'Together with planning poker' },
      { p: 'The most common way to decide story points is to play [planning poker](/en/what-is-planning-poker): everyone secretly picks a value, the cards flip together, and the differences get discussed. SprintMasası runs this in your browser without an account.' },
      { cta: true },
    ],
  },
  {
    id: 'privacy',
    lang: 'en',
    path: '/en/privacy',
    title: 'Privacy | SprintMasası',
    description:
      'What information SprintMasası processes and how long it keeps it. No accounts, no cookies, no tracking: rooms live only in server memory.',
    h1: 'Privacy',
    lead:
      'SprintMasası does not ask for an account, email or phone number; it uses no cookies and contains no ads or trackers. Information in a room is kept only in server memory and is deleted when the room closes.',
    blocks: [
      { h2: 'What information is processed?' },
      { p: 'What you type and choose in a room is sent to the server, because everyone at the table has to see the same thing:' },
      { ul: [
        'your nickname and avatar,',
        'your votes and the chosen deck,',
        'the room name, topic, and any ticket titles, links and notes,',
        'the room password (stored only as an irreversible hash).',
      ] },
      { p: 'This information is not written to disk or to a database; it lives only in the memory of the running server.' },
      { h2: 'How long is it kept?' },
      { ul: [
        'When the dealer closes the room, the room and everything in it is deleted.',
        'A room nobody is connected to is deleted automatically 7 days after its last activity.',
        'When the server restarts or a new version is deployed, all rooms are deleted.',
      ] },
      { h2: 'What is stored in your browser' },
      { p: 'So you can return to the same seat when you refresh the page, a seat key is kept in your browser\'s local storage (localStorage). Your nickname, avatar, theme, sound and language preferences are stored too. These are not cookies, are not used for tracking, and you can delete them by clearing your browser data.' },
      { h2: 'Logs and IP addresses' },
      { p: 'The application\'s logs contain only the room code and the type of event (such as "room created"); names, votes and ticket content are never logged. To limit abuse, your IP address is used in memory for rate-limit counters that last a few minutes and is not stored permanently.' },
      { p: 'Render, which hosts the server, may keep IP addresses in its own infrastructure logs. Those records are outside our control; see the [Render privacy policy](https://render.com/privacy) for details.' },
      { h2: 'Statistics' },
      { p: 'Only totals are kept, such as how many rooms were opened, the average number of participants and how many rounds were revealed. These numbers cannot be linked to people or to the content of rooms. No third-party analytics, advertising or tracking tools are used.' },
      { h2: 'Third parties' },
      { p: 'Fonts, images and avatars come from our own server; no Google Fonts, CDN or external avatar service is called. If you click a ticket link, the rules of that site apply.' },
      { h2: 'Security and things to watch' },
      { ul: [
        'The connection is encrypted with HTTPS.',
        'Room codes are generated randomly and cannot be guessed; however, anyone who knows the link can enter a room without a password.',
        'If your ticket titles contain internal company information, set a room password.',
        'Do not type passwords, personal data or secrets into ticket and note fields.',
      ] },
      { h2: 'Your rights and contact' },
      { p: 'To exercise your rights under data protection laws (KVKK and GDPR) or to ask a question, contact us through the [GitHub project page](https://github.com/rossven/scrum-poker/issues). Because room information is not stored permanently, there is usually no record left to delete. The party processing the data is the project owner who operates SprintMasası (GitHub: rossven).' },
      { h2: 'Changes' },
      { p: 'If the application changes, this page is updated; the date at the bottom shows the last update.' },
    ],
    noCta: true,
  },
];
